/**
 * Shared In-Memory Store for Demo, Offline Fallback & Unit Testing Sessions.
 * Ensures consistent state across database.js and database_extensions.js.
 */

export const demoStore = {
  nextCustomerId: 10,
  nextEntryId: 20,
  nextMedId: 30,
  customers: [
    {
      customer_id: 1,
      phone_number: '9848012345',
      name: 'Ramesh Patel',
      village: 'Kompally',
      address: 'Plot 42, Main Road',
      created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
      deleted_at: null,
      entries: [
        {
          entry_id: 1,
          due_amount: 450,
          total_amount: 850,
          amount_paid: 400,
          entry_date: new Date(Date.now() - 86400000 * 2).toISOString(),
          deleted_at: null,
        },
      ],
    },
    {
      customer_id: 2,
      phone_number: '9876543210',
      name: 'Priya Sharma',
      village: 'Medchal',
      address: 'House # 12-4',
      created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
      deleted_at: null,
      entries: [],
    },
    {
      customer_id: 3,
      phone_number: '9123456789',
      name: 'Anita Rao',
      village: 'Gandipet',
      address: 'Near Old Water Tank',
      created_at: new Date(Date.now() - 86400000 * 15).toISOString(),
      deleted_at: null,
      entries: [
        {
          entry_id: 2,
          due_amount: 0,
          total_amount: 300,
          amount_paid: 300,
          entry_date: new Date(Date.now() - 86400000 * 1).toISOString(),
          deleted_at: null,
        },
      ],
    },
  ],
  entries: [
    {
      entry_id: 1,
      customer_id: 1,
      customer_name: 'Ramesh Patel',
      phone_number: '9848012345',
      entry_date: new Date(Date.now() - 86400000 * 2).toISOString(),
      total_amount: 850,
      amount_paid: 400,
      due_amount: 450,
      notes: 'Blood pressure tablets & pain relief',
      deleted_at: null,
      medicines: [
        {
          id: 1,
          entry_id: 1,
          medicine_name: 'Amlodipine 5 mg',
          quantity: 30,
          unit: 'tablets',
          unit_price: 15,
          price: 450,
          original_price: 450,
          discount_percent: 0,
        },
        {
          id: 2,
          entry_id: 1,
          medicine_name: 'Paracetamol 650 mg',
          quantity: 20,
          unit: 'tablets',
          unit_price: 20,
          price: 400,
          original_price: 400,
          discount_percent: 0,
        },
      ],
    },
    {
      entry_id: 2,
      customer_id: 3,
      customer_name: 'Anita Rao',
      phone_number: '9123456789',
      entry_date: new Date(Date.now() - 86400000 * 1).toISOString(),
      total_amount: 300,
      amount_paid: 300,
      due_amount: 0,
      notes: 'Monthly regular vitamins & paracetamol',
      deleted_at: null,
      medicines: [
        {
          id: 3,
          entry_id: 2,
          medicine_name: 'Paracetamol 500 mg',
          quantity: 10,
          unit: 'tablets',
          unit_price: 12,
          price: 120,
          original_price: 120,
          discount_percent: 0,
        },
        {
          id: 4,
          entry_id: 2,
          medicine_name: 'Vitamin D3',
          quantity: 1,
          unit: 'strip',
          unit_price: 180,
          price: 180,
          original_price: 180,
          discount_percent: 0,
        },
      ],
    },
  ],
  shopProfile: {
    shop_name: 'Sunrise Pharmacy',
    shop_license_no: '20B/1234/2024',
    license_20b: '20B/1234/2024',
    license_21b: '21B/5678/2024',
    shop_license_validity: '2028-12-31',
    shop_phone: '+91 98765 43210',
    pharmacist_name: 'Maya, B.Pharm',
    pharmacist_phone: '9848012345',
    pharmacist_license_validity: '2029-06-30',
  },
};
